refresh_rate: 30 seconds

appenders:
  file:
    kind: file
    path: "log/app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {l} | {f}:{L} | {m}{n}"
  console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {l} | {f}:{L} | {m}{n}"

root:
  level: info
  appenders:
    - file
    - console

loggers:
  app:
    level: info